### ISSUE TITLE
[Design] 글쓰기 View 레이아웃 구현

### ISSUE THREAD

**Issue by vanism2091** [DaangnMarket/DaangnMarket-iOS#48]
## 🥕  Issue
글쓰기 view를 구현합니다. 모달로 올라와요.

## 📝  To-do

- [ ] 사진
- [ ] 글 제목
- [ ] 카테고리 선택 - 서버
- [ ] 설명
- [ ] 가격

- [ ] 인원 : 모으고 싶은 인원 -> 이건 당근에 없으니까 안해도 ㄱㅊ
- [ ] 날짜 선택 (optional)
- [ ] 거래 희망 장소 선택 : 당근처럼 지도..:) (optional)
- [ ] 링크(optional)
